name: yusa_box
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  dynamic_color: ^1.6.8
  http: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
